/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcompanharRouteImport } from './routes/acompanhar'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as DoarRouteImport } from './routes/doar'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as DoacaoEnviadaRouteImport } from './routes/doacao.enviada'
import { Route as NecessidadesIndexRouteImport } from './routes/necessidades.index'
import { Route as NecessidadesIdRouteImport } from './routes/necessidades.$id'
import { Route as AdminDoacoesIndexRouteImport } from './routes/admin.doacoes.index'
import { Route as AdminDoacoesIdRouteImport } from './routes/admin.doacoes.$id'
import { Route as AdminNecessidadesIndexRouteImport } from './routes/admin.necessidades.index'
import { Route as AdminNecessidadesIdRouteImport } from './routes/admin.necessidades.$id'
import { Route as AdminNecessidadesNovaRouteImport } from './routes/admin.necessidades.nova'
import { Route as AdminNecessidadesIdEditarRouteImport } from './routes/admin.necessidades.$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanharRoute = AcompanharRouteImport.update({
  id: '/acompanhar',
  path: '/acompanhar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const DoarRoute = DoarRouteImport.update({
  id: '/doar',
  path: '/doar',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/admin/relatorios',
  path: '/admin/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const DoacaoEnviadaRoute = DoacaoEnviadaRouteImport.update({
  id: '/doacao/enviada',
  path: '/doacao/enviada',
  getParentRoute: () => rootRouteImport,
} as any)
const NecessidadesIndexRoute = NecessidadesIndexRouteImport.update({
  id: '/necessidades/',
  path: '/necessidades/',
  getParentRoute: () => rootRouteImport,
} as any)
const NecessidadesIdRoute = NecessidadesIdRouteImport.update({
  id: '/necessidades/$id',
  path: '/necessidades/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDoacoesIndexRoute = AdminDoacoesIndexRouteImport.update({
  id: '/admin/doacoes/',
  path: '/admin/doacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDoacoesIdRoute = AdminDoacoesIdRouteImport.update({
  id: '/admin/doacoes/$id',
  path: '/admin/doacoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNecessidadesIndexRoute = AdminNecessidadesIndexRouteImport.update({
  id: '/admin/necessidades/',
  path: '/admin/necessidades/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNecessidadesIdRoute = AdminNecessidadesIdRouteImport.update({
  id: '/admin/necessidades/$id',
  path: '/admin/necessidades/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNecessidadesNovaRoute = AdminNecessidadesNovaRouteImport.update({
  id: '/admin/necessidades/nova',
  path: '/admin/necessidades/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNecessidadesIdEditarRoute =
  AdminNecessidadesIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AdminNecessidadesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acompanhar': typeof AcompanharRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/doar': typeof DoarRoute
  '/faq': typeof FaqRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/doacao/enviada': typeof DoacaoEnviadaRoute
  '/necessidades/$id': typeof NecessidadesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/necessidades/': typeof NecessidadesIndexRoute
  '/admin/doacoes/$id': typeof AdminDoacoesIdRoute
  '/admin/necessidades/$id': typeof AdminNecessidadesIdRouteWithChildren
  '/admin/necessidades/nova': typeof AdminNecessidadesNovaRoute
  '/admin/doacoes/': typeof AdminDoacoesIndexRoute
  '/admin/necessidades/': typeof AdminNecessidadesIndexRoute
  '/admin/necessidades/$id/editar': typeof AdminNecessidadesIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acompanhar': typeof AcompanharRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/doar': typeof DoarRoute
  '/faq': typeof FaqRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/doacao/enviada': typeof DoacaoEnviadaRoute
  '/necessidades/$id': typeof NecessidadesIdRoute
  '/admin': typeof AdminIndexRoute
  '/necessidades': typeof NecessidadesIndexRoute
  '/admin/doacoes/$id': typeof AdminDoacoesIdRoute
  '/admin/necessidades/$id': typeof AdminNecessidadesIdRouteWithChildren
  '/admin/necessidades/nova': typeof AdminNecessidadesNovaRoute
  '/admin/doacoes': typeof AdminDoacoesIndexRoute
  '/admin/necessidades': typeof AdminNecessidadesIndexRoute
  '/admin/necessidades/$id/editar': typeof AdminNecessidadesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acompanhar': typeof AcompanharRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/doar': typeof DoarRoute
  '/faq': typeof FaqRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/doacao/enviada': typeof DoacaoEnviadaRoute
  '/necessidades/$id': typeof NecessidadesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/necessidades/': typeof NecessidadesIndexRoute
  '/admin/doacoes/$id': typeof AdminDoacoesIdRoute
  '/admin/necessidades/$id': typeof AdminNecessidadesIdRouteWithChildren
  '/admin/necessidades/nova': typeof AdminNecessidadesNovaRoute
  '/admin/doacoes/': typeof AdminDoacoesIndexRoute
  '/admin/necessidades/': typeof AdminNecessidadesIndexRoute
  '/admin/necessidades/$id/editar': typeof AdminNecessidadesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acompanhar'
    | '/como-funciona'
    | '/doar'
    | '/faq'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/admin/relatorios'
    | '/doacao/enviada'
    | '/necessidades/$id'
    | '/admin/'
    | '/necessidades/'
    | '/admin/doacoes/$id'
    | '/admin/necessidades/$id'
    | '/admin/necessidades/nova'
    | '/admin/doacoes/'
    | '/admin/necessidades/'
    | '/admin/necessidades/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acompanhar'
    | '/como-funciona'
    | '/doar'
    | '/faq'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/admin/relatorios'
    | '/doacao/enviada'
    | '/necessidades/$id'
    | '/admin'
    | '/necessidades'
    | '/admin/doacoes/$id'
    | '/admin/necessidades/$id'
    | '/admin/necessidades/nova'
    | '/admin/doacoes'
    | '/admin/necessidades'
    | '/admin/necessidades/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/acompanhar'
    | '/como-funciona'
    | '/doar'
    | '/faq'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/admin/relatorios'
    | '/doacao/enviada'
    | '/necessidades/$id'
    | '/admin/'
    | '/necessidades/'
    | '/admin/doacoes/$id'
    | '/admin/necessidades/$id'
    | '/admin/necessidades/nova'
    | '/admin/doacoes/'
    | '/admin/necessidades/'
    | '/admin/necessidades/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcompanharRoute: typeof AcompanharRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  DoarRoute: typeof DoarRoute
  FaqRoute: typeof FaqRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  DoacaoEnviadaRoute: typeof DoacaoEnviadaRoute
  NecessidadesIdRoute: typeof NecessidadesIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  NecessidadesIndexRoute: typeof NecessidadesIndexRoute
  AdminDoacoesIdRoute: typeof AdminDoacoesIdRoute
  AdminNecessidadesIdRoute: typeof AdminNecessidadesIdRouteWithChildren
  AdminNecessidadesNovaRoute: typeof AdminNecessidadesNovaRoute
  AdminDoacoesIndexRoute: typeof AdminDoacoesIndexRoute
  AdminNecessidadesIndexRoute: typeof AdminNecessidadesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhar': {
      id: '/acompanhar'
      path: '/acompanhar'
      fullPath: '/acompanhar'
      preLoaderRoute: typeof AcompanharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doar': {
      id: '/doar'
      path: '/doar'
      fullPath: '/doar'
      preLoaderRoute: typeof DoarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doacao/enviada': {
      id: '/doacao/enviada'
      path: '/doacao/enviada'
      fullPath: '/doacao/enviada'
      preLoaderRoute: typeof DoacaoEnviadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/necessidades/': {
      id: '/necessidades/'
      path: '/necessidades'
      fullPath: '/necessidades/'
      preLoaderRoute: typeof NecessidadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/necessidades/$id': {
      id: '/necessidades/$id'
      path: '/necessidades/$id'
      fullPath: '/necessidades/$id'
      preLoaderRoute: typeof NecessidadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/doacoes/': {
      id: '/admin/doacoes/'
      path: '/admin/doacoes'
      fullPath: '/admin/doacoes/'
      preLoaderRoute: typeof AdminDoacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/doacoes/$id': {
      id: '/admin/doacoes/$id'
      path: '/admin/doacoes/$id'
      fullPath: '/admin/doacoes/$id'
      preLoaderRoute: typeof AdminDoacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/necessidades/': {
      id: '/admin/necessidades/'
      path: '/admin/necessidades'
      fullPath: '/admin/necessidades/'
      preLoaderRoute: typeof AdminNecessidadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/necessidades/$id': {
      id: '/admin/necessidades/$id'
      path: '/admin/necessidades/$id'
      fullPath: '/admin/necessidades/$id'
      preLoaderRoute: typeof AdminNecessidadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/necessidades/nova': {
      id: '/admin/necessidades/nova'
      path: '/admin/necessidades/nova'
      fullPath: '/admin/necessidades/nova'
      preLoaderRoute: typeof AdminNecessidadesNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/necessidades/$id/editar': {
      id: '/admin/necessidades/$id/editar'
      path: '/editar'
      fullPath: '/admin/necessidades/$id/editar'
      preLoaderRoute: typeof AdminNecessidadesIdEditarRouteImport
      parentRoute: typeof AdminNecessidadesIdRoute
    }
  }
}

interface AdminNecessidadesIdRouteChildren {
  AdminNecessidadesIdEditarRoute: typeof AdminNecessidadesIdEditarRoute
}

const AdminNecessidadesIdRouteChildren: AdminNecessidadesIdRouteChildren = {
  AdminNecessidadesIdEditarRoute: AdminNecessidadesIdEditarRoute,
}

const AdminNecessidadesIdRouteWithChildren =
  AdminNecessidadesIdRoute._addFileChildren(AdminNecessidadesIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcompanharRoute: AcompanharRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  DoarRoute: DoarRoute,
  FaqRoute: FaqRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  DoacaoEnviadaRoute: DoacaoEnviadaRoute,
  NecessidadesIdRoute: NecessidadesIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  NecessidadesIndexRoute: NecessidadesIndexRoute,
  AdminDoacoesIdRoute: AdminDoacoesIdRoute,
  AdminNecessidadesIdRoute: AdminNecessidadesIdRouteWithChildren,
  AdminNecessidadesNovaRoute: AdminNecessidadesNovaRoute,
  AdminDoacoesIndexRoute: AdminDoacoesIndexRoute,
  AdminNecessidadesIndexRoute: AdminNecessidadesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
